version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "America/Guayaquil"
    allow:
      - dependency-type: "all"
    ignore:
      # Ignore patch updates for all packages
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    commit-message:
      prefix: "pip"
      include: "scope"
    labels:
      - "pip"
      - "dependencies"
    open-pull-requests-limit: 2
    reviewers:
      - "@solnustec/backend"
